### ISSUE TITLE
Fix json error in authentication

### ISSUE THREAD

**Issue by sciurius** [Hexxeh/spotify-websocket-api#18]
spotify_web/spotify.py, line 192, should be "resp.json" without parens.
Line 199 should be "resp_json" instead of "resp.json()".

**Comment by juanriaza** [comment]
@sciurius probably caused by an outdated version of `requests`

**Comment by rodrigoaguilera** [comment]
I can confirm that the bug is due to outdated version of requests
Is there a way to control the version?

**Comment by juanriaza** [comment]
@rodrigoaguilera with a proper `setup.py`

**Comment by sciurius** [comment]
[Quoting Juan Riaza, on January 21 2013, 16:00, in "Re: [spotify-websock"]

> @sciurius probably caused by an outdated version of requests

I have python-requests-0.14.1-1.fc17.noarch which is the latest
version distributed with Fedora 17.

-- Johan

**Comment by juanriaza** [comment]
@sciurius you should get a 1.X version

**Comment by Hexxeh** [comment]
But REALLY old compared to the version in pip.

**Comment by sciurius** [comment]
Juan Riaza notifications@github.com writes:

> @sciurius you should get a 1.X version

I installed 1.1.0 and updated spotify-websocket-api to the current git
version.

The json problems are gone, good.

However, when I want to play something, my MPD client complains
"problems decoding http://localhost:8080?uri-spotify:track:....".

Note that before the upgrade it did play spotify tracks.

Any idea what could be going wrong?

-- Johan
