### ISSUE TITLE
Facebook credentials

### ISSUE THREAD

**Issue by buschtoens** [Hexxeh/spotify-websocket-api#20]
I don't know, if I'm just too stupid, or if Facebook login credentials really don't work.

**Comment by Hexxeh** [comment]
Set a device password via Spotify's website and use that.

**Comment by buschtoens** [comment]
Ehrmahgerd, thank you! :)

**Comment by buschtoens** [comment]
But still. Wouldn't it be nice to login via Facebook?

**Comment by Hexxeh** [comment]
You can't as a third party app.

**Comment by buschtoens** [comment]
Ah, what a tragedy... Anyways, thanks. I love the work you've done here.

**Comment by Hexxeh** [comment]
To be fair, giving your Facebook password to a third party app is a bad
idea. Device passwords make sense.
