### ISSUE TITLE
Trying to rebuild in Node.js

### ISSUE THREAD

**Issue by buschtoens** [Hexxeh/spotify-websocket-api#22]
I'm stunned by your project! Now I'm trying to rebuild it in Node.js, but already encounter a problem: https://github.com/Hexxeh/spotify-websocket-api/blob/master/spotify_web/spotify.py#L184

How do you find the secret? When I reuest the page I get two redirects and finally end up on Rick. What am I doing wrong?

**Comment by Hexxeh** [comment]
Which secret?

**Comment by buschtoens** [comment]
Sorry, somehow had the wrong link to the file. Edited the first message.

**Comment by TooTallNate** [comment]
@silvinci I take it you haven't yet seen: https://github.com/TooTallNate/node-spotify-web

**Comment by Hexxeh** [comment]
Oh, the album/track? They're arbitrary, I think you can use any.

**Comment by Hexxeh** [comment]
Your playback code is awesome, by the way. I'm not much of a Node fan, but
that's very slick.

**Comment by buschtoens** [comment]
@TooTallNate You are so right. I think I love you!
@Hexxeh Case closed. Already found a port... or the port found me. :D
