### ISSUE TITLE
Sound Quality

### ISSUE THREAD

**Issue by Taranis01** [Hexxeh/spotify-websocket-api#25]
Is 'mp3160' the onliest available quality, or how are other variables called?

**Comment by Hexxeh** [comment]
It's the highest currently available via this API.

**Comment by Taranis01** [comment]
would be great to use a quality, made for good ears. Is this a restriction by Spotify's API?

**Comment by Hexxeh** [comment]
Yes. They're only offering 160k MP3 at the moment.

**Comment by wuestkamp** [comment]
Doesn't this one work with the premium account and better sound quality?

**Comment by jhvst** [comment]
> Doesn't this one work with the premium account and better sound quality?

Premium account does not affect the stream quality even if you try to use different streams inside of the track object nor does Spotify respond to other streams than mp3160.

**Comment by tsmithe** [comment]
I wonder -- now that the new web player is released -- is there a 320kbps stream available?
