### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by richard-ive** [Hexxeh/spotify-websocket-api#28]
Hi there, firstly, thank you for this awesome tool! It's really useful!

On Thursday, because of the authentication fix, I decided to re-install on my Raspberry Pi. Unfortunately I'm getting the errors in this pastebin: http://pastebin.com/yu0w9Qsr. I was wondering if you could help me figure out what it is? Sorry, I know it's not a direct issue with your code.

After the compilation failed I decided to see if the example client would work. It kind of does, but the audio is very quiet and fuzzy. I assume it must have something to do with the compilation failure?

Thanks again!

**Comment by Hexxeh** [comment]
You have a problem is that lxml failed to compile. Not sure why that'd make
audio playback fuzzy though, I don't think it would...

**Comment by richard-ive** [comment]
Need to find out what the compilation issue is on my Pi.

The sounds was an issue with alsamixer.

Closed the ticket :)

Thanks again!
