### ISSUE TITLE
Can't get mp3 urls with free account anymore

### ISSUE THREAD

**Issue by redondo-se** [Hexxeh/spotify-websocket-api#32]
Just started playing with this API a couple days ago.  At first, I was able to fetch mp3 urls with my Spotify free account.  But, now I can't.  I even created a new account and a new facebook account, linked them together, and tried with that account, but that doesn't work either.  Did Spotify do something on their side to disable it?

**Comment by rodrigoaguilera** [comment]
And with a paid account?

**Comment by Hexxeh** [comment]
They officially launched today, and as part of that they appear have to blocked out access for non-Premium users via this API. I expected this to happen and whilst I can see how they've done it, I don't intend to attempt to circumvent this restriction.

If you like Spotify, buy a Premium account to support them: show the industry this is a great model for legally listening to music.

Closing.

**Comment by rodrigoaguilera** [comment]
There's going to be better quality options? I'm thinking about paying but I'm not convinced if it's only for 160kbps mp3

**Comment by lupocos** [comment]
I know the thread has been closed, but I'll ask it anyway: 

Could anybody confirm whether this API works with "Unlimited" accounts (4.99 £/month, no mobile) as well as with Premium ones? 
I already have Premium -- I can confirm it's still working after the changes -- but I was wondering if the websocket-api would still work if I decided to switch to Unlimited.
Thanks.

**Comment by rodrigoaguilera** [comment]
And I think it should be fixed to give an error message stating that you are not Premium
