### ISSUE TITLE
Cloudfront "Access Denied"

### ISSUE THREAD

**Issue by veered** [Hexxeh/spotify-websocket-api#33]
Whenever I try to play a track Cloudfront tells me "Access Denied". I have the Unlimited plan and I am able to retrieve metadata about tracks. The url generated by the "play.py" example is "http://dsu0uct5x2puz.cloudfront.net/mp3/7731762c563cbd56a8af864f9924afe1e4465cea?Expires=1363303786&Signature=l7KXuAHYqNJbfEqEV0gKITZZ2hl-1kphLVSvA2IXDQ03nhOVL5k1rOEBdBk96YaS1uHGy~qIKLPb4Mv9f0~JXPnL3rrqgKWC0qf9yuILGtfmH2NprKAfKFj2uOCMH8nSEcSoN8jhT9zI9tqu7YdI2bMjA7hkD3gguW5YbJLZKi0_&Key-Pair-Id=APKAIJ6GQLKYCDRS5HFA".

I checked out the repo about an hour ago, so it should be up to date.

**Comment by Hexxeh** [comment]
The URLs have a very short expiry of only a few seconds set. If you don't
use them very quickly, they expire.

**Comment by TooTallNate** [comment]
Close?

**Comment by Hexxeh** [comment]
Yup.
