### ISSUE TITLE
rate request error

### ISSUE THREAD

**Issue by l3iggs** [Hexxeh/spotify-websocket-api#40]
Am I doing something wrong? I'm seeing rate request errors when running the test.py here:

``` bash
$ PASSWORD=**** USERNAME=**** ./test.py
[ERROR] Rate request error
.[ERROR] Rate request error
.
----------------------------------------------------------------------
Ran 2 tests in 14.271s

OK
```

**Comment by Hexxeh** [comment]
No, it's possibly just something that changed server side. It seems the
servers have been trying to block this out in a few places.

**Comment by l3iggs** [comment]
Oh. What a bummer. So this could be the end of open source access?
Am I being too dramatic?

**Comment by Hexxeh** [comment]
It just needs somebody to throw some time at it to fix it again. I don't
have time right now.

**Comment by bih** [comment]
Is there any documentation on 'fixing' this issue?

**Comment by l3iggs** [comment]
Is it fair to consider this project dead?

**Comment by Hexxeh** [comment]
No, I just haven't figured out what they changed that killed this yet.
Patches are very much welcome.

**Comment by l3iggs** [comment]
What makes you think this is a solvable problem? If I were Spotify, I would take steps to make it impossible for 3rd party clients to use the service.

**Comment by Hexxeh** [comment]
It's essentially impossible to make it impossible. The most they can do is
make it very hard.

**Comment by l3iggs** [comment]
Maybe this project helps here: https://github.com/vivekseth/Spotify-Downloader

**Comment by Hexxeh** [comment]
No, people trying to pirate music certainly doesn't help.

**Comment by l3iggs** [comment]
Well I figure if that code works it may contain some clue that could help in understanding what Spotify change broke this project.

**Comment by j-mie** [comment]
@l3iggs it's because of that Spotify changed the backend to stop stuff like this working. I know something called mopidy is able to stream Spotify and search it so there might be some help in there.

**Comment by elliottwilliams** [comment]
I believe Mopidy is based on [libspotify]( https://developer.spotify.com/technologies/libspotify/), Spotify's official API. The biggest drawbacks of libspotify, in my opinion, are that it's Premium-only and that you get steams of raw audio, not mp3's.

**Comment by Schischu** [comment]
Don't forget that libspotify is not available for all platforms, so projects like this one are atm the only hope for mipsel and sh4 devices.

**Comment by l3iggs** [comment]
fixed! thank you @Hexxeh
