### ISSUE TITLE
320kbps playback

### ISSUE THREAD

**Issue by tsmithe** [Hexxeh/spotify-websocket-api#52]
It looks like the streams here are 160kbps, but Spotify Premium can provide 320kbps streams. Is there any method to get those streams here?

**Comment by rodrigoaguilera** [comment]
https://github.com/Hexxeh/spotify-websocket-api/issues/25

**Comment by tsmithe** [comment]
Ah. Well, then, when the web player supports it, I'm sure this API will too!
