### ISSUE TITLE
Stuck in some tracks

### ISSUE THREAD

**Issue by kendersec** [Hexxeh/spotify-websocket-api#7]
I've tried getting the metadata for certain songs and it just locks forever. E.g.

```
track = 'spotify:track:7FzURKB88npEvZ4Jzv0AEw'

track_obj = sp.metadata_request(track)

print track_obj
```

It never gets to the print statement. I don't know if this is an issue of the library or it's on the Spotify servers but we could perhaps have a timeout mechanism?

**Comment by Hexxeh** [comment]
This looks like an internal library problem. You can enable verbose logging by changing the log level in spotify.py from 1 to 3. Spotify is returning metadata, we're just not handling it properly. Investigating this now.

**Comment by kendersec** [comment]
If it is of any help, I believe it also happens with spotify:track:52dhxwrC5RgPcuxb8SrX0k

**Comment by Hexxeh** [comment]
It appears it's a bug in the restriction handling. You might notice that track shows a little chain icon in the real client.

This means it's no longer available in your area, but Spotify has a replacement it can play for you automatically.

This API doesn't handle that properly yet, and I'm kinda stuck on how to deal with it correctly, looking for help with that.

I'm disabling restriction handling for now by default, but note you wouldn't be able to play this track, even though you can get it's metadata.

**Comment by kendersec** [comment]
Like you said the problem is with the restriction handling, I think the problem is within WrapAsync because get_data() does never return on the second call (with the viable alternative).

A couple more things.

https://github.com/Hexxeh/spotify-websocket-api/blob/master/spotify_web/spotify.py#L264

I don't think you need the recursion there as metadata_request is bound to call on recurse_alternatives anyway. The problem here is that even if we remove that recursion metadata_request does never return blocked by the above get_data() never returning [no idea why yet].

No sure why but I had to change:

https://github.com/Hexxeh/spotify-websocket-api/blob/master/spotify_web/spotify.py#L155

so that it is resp.json and not resp.json(), I imagine this is due to my requests version but it might be interesting to look into it (I might have a look myself later in the week if I have time)

**Comment by kendersec** [comment]
Further on the blocking, it seems that we are making the metadata_request, which creates a send event and for some reason we wait forever for the response from the server.

Not sure if this will help but...

```
[DEBUG] sent {"args":[0,"CjRobTovL21ldGFkYXRhL3RyYWNrL2ZjMDg2ZDFlZWJhNTQ5NzhiYTQwZDAzM2FmNGY0ODMwGgNH\nRVQ=\n"],"name":"sp/hm_b64","id":"3"}
[DEBUG] recv {"id":3,"result":["CjRobTovL21ldGFkYXRhL3RyYWNrL2ZjMDg2ZDFlZWJhNTQ5NzhiYTQwZDAzM2FmNGY0ODMwEhp2bmQuc3BvdGlmeS9tZXRhZGF0YS10cmFjayCQAzIZCg9NQy1DYWNoZS1Qb2xpY3kSBnB1YmxpYzINCgZNQy1UVEwSAzMwMA==","ChD8CG0e66VJeLpA0DOvT0gwEjhMZSBOb3p6ZSBkaSBGaWdhcm8sIEsuNDkyLCBBY3QgSUlJOiBDYW56b25ldHRhIHN1bGwnYXJpYRqlAgoQQbZQjzsiSG2Fa6uNjsChERIWMTAwIEJlc3QgRmlsbSBDbGFzc2ljcxojChAZM06v+j9PIoLiUeNmEeJvEg9WYXJpb3VzIEFydGlzdHMqDEVNSSBDbGFzc2ljczIDCKwfSh4KFIryoUGlNRtpRdh1OWwjCphFV4v2EAAY2AQg2ARKHgoUzVBoc+7+KwzSI4Yb38DiZFmMfgAQARiAASCAAUoeChQKLCU+feGlt79ltpzSn9y9F5fSeRACGIAKIIAKigFgCh4KFIryoUGlNRtpRdh1OWwjCphFV4v2EAAY2AQg2AQKHgoUzVBoc+7+KwzSI4Yb38DiZFmMfgAQARiAASCAAQoeChQKLCU+feGlt79ltpzSn9y9F5fSeRACGIAKIIAKIiIKEN3s751cgkCKgS1LV6KFDjASDkdpYW5uYSBSb2xhbmRpIiEKEJvrp6lHDEM3nIDgaQ5pmAoSDUZlbGljaXR5IExvdHQiMQoQfbuERYsERXSpDEEA9n3HJBIdTG9uZG9uIFBoaWxoYXJtb25pYyBPcmNoZXN0cmEiIwoQIsxqjiCnRUqiPDUEcymx/RIPQmVybmFyZCBIYWl0aW5rKBIwCjiM6hZAPlIUCgRpc3JjEgxHQkFZQzg3MDM1MzZaFAgACAESDkFTR1VNUFBSVU1VU1ZJYhgKFAZ2hUYuhTdg9qHQPj4MDNOsBLRzEAJiGAoUcp1zdPavjz8v8spG6OtCxhP8x+cQAWIYChT0xvlP6pCi0zmfG7Ri/w7GbhgkaxAAYhgKFCdq7d1Ww6Bg732w40EFV0/jK7CREARiAhAFaqIBChA6E/eZ+mRLfpU2wt/ac9mBWiIIAAgBGhxBRkFTQk1HTEdVS0dNS01NTVBQU1VNVVNWQVZJYhgKFOWPPAAHT8CJB+P2lkpmrcDAPkq5EAJiGAoUL5SwfyU4Dj5FAmP19bE9IZ9Lu7oQAWIYChR86pyCMBNSi2I4iMF27aJ2ZysvaxAAYhgKFFBfZBvD4iF80Kcpsi2E+L41R3h3EARiAhAFehgKFBPiXx6g/RRUfDEMj/3rlAZuPbHPEAY="]}
[DEBUG] sent {"args":[0,"CjRobTovL21ldGFkYXRhL3RyYWNrLzNhMTNmNzk5ZmE2NDRiN2U5NTM2YzJkZmRhNzNkOTgxGgNH\nRVQ=\n"],"name":"sp/hm_b64","id":"4"}
```

You can see the original request with id:3, then the response to that one which triggers the restriction and a request for the alternative (id:4) then it hangs.

I've observed that this happens randomly with other tracks too but when you retry everything seems to go smoothly, perhaps it is just a matter of setting up a retrial mechanism?

[Of couse I'm just guessing here and might have completely missed on what the actual problem is...]

**Comment by Hexxeh** [comment]
This should be fixed in the latest commit, can you verify?

<pre>
$ ./blocking.py hexxeh [password] restriction spotify:track:7FzURKB88npEvZ4Jzv0AEw
Track is available!
$ ./blocking.py hexxeh [password] track spotify:track:7FzURKB88npEvZ4Jzv0AEw
Le Nozze di Figaro, K.492, Act III: Canzonetta sull'aria
</pre>

**Comment by kendersec** [comment]
Yes, it works now, thanks :)

**Comment by kendersec** [comment]
I've got another track that seems to be playing up with the restrictions. Here is the log:

```
[NOTICE] Connecting to wss://lon2-linkap-a4.lon.spotify.com:443
[NOTICE] Logging in
[DEBUG] sent {"args":["201","c57abe4de3c78bcd67eeea918efda23c89fa25ed","{\"ip\":\"81.101.204.171\",\"timestamp\":1356698176,\"ttl\":900,\"useragent\":\"spotify-websocket-api (Chrome\\/13.37 compatible-ish)\",\"version\":30100000,\"token\":\"NAo_CicKDVNwb3RpZnktdXNlcnMSDGNvbmNpc2VhdGxhcxoDmAEBJcSV3VASFPHjKeAuSy_HyxagzicAaQz1O4xM\"}"],"name":"connect","id":"0"}
[DEBUG] recv {"id":0,"result":"ok"}
[DEBUG] sent {"args":[],"name":"sp/user_info","id":"1"}
[DEBUG] recv {"message":["do_work","try { console.log('Connected to 1930.0'); } catch(_) {}; this.reply('v1');"]}
[DEBUG] Got do_work message, payload: try { console.log('Connected to 1930.0'); } catch(_) {}; this.reply('v1');
[DEBUG] sent {"args":["v1"],"name":"sp/work_done","id":"2"}
[DEBUG] recv {"message":["login_complete"]}
[DEBUG] recv {"id":1,"result":{"ab_test_group":"269","ads":"1","catalogue":"free","country":"GB","license_agreements":"0.8.8-GB","link_tutorial_completed":"0","post_open_graph":"-3","user":"conciseatlas","wanted_licenses":"0.8.8-GB"}}
[DEBUG] sent {"args":[0,"CjRobTovL21ldGFkYXRhL3RyYWNrLzNjMTc4OWZhM2Y2YTQwMTZhYmVhNWI3MGE0OWYzOTZlGgNH\nRVQ=\n"],"name":"sp/hm_b64","id":"3"}
[DEBUG] recv {"id":2,"result":"ok"}
[DEBUG] Got ack for message reply
[DEBUG] recv {"id":3,"result":["CjRobTovL21ldGFkYXRhL3RyYWNrLzNjMTc4OWZhM2Y2YTQwMTZhYmVhNWI3MGE0OWYzOTZlEhp2bmQuc3BvdGlmeS9tZXRhZGF0YS10cmFjayCQAzIZCg9NQy1DYWNoZS1Qb2xpY3kSBnB1YmxpYzINCgZNQy1UVEwSAzMwMA==","ChA8F4n6P2pAFqvqW3CknzluEjdDYXByaWNjaW8gZXNwYWdub2wsIE9wLiAzNDogQWxib3JhZGE6IFZpdm8gZSBzdHJlcGl0b3NvGqkCChA6K2aJNrNCub9f0HKa1WiXEh1SaW1za3ktS29yc2Frb3YgKFRoZSBCZXN0IE9mKRojChAZM06v+j9PIoLiUeNmEeJvEg9WYXJpb3VzIEFydGlzdHMqBU5heG9zMgcImh8QDBggSh4KFGgVpM9l4+sbLzJtOQkQdte2VuyAEAAY2AQg2ARKHgoUUSmDpkcaesOm8TTwl5xOUs1nyzMQARiAASCAAUoeChRvUIFuFmU1tNso4cx370VZOxyoXhACGIAKIIAKigFgCh4KFGgVpM9l4+sbLzJtOQkQdte2VuyAEAAY2AQg2AQKHgoUUSmDpkcaesOm8TTwl5xOUs1nyzMQARiAASCAAQoeChRvUIFuFmU1tNso4cx370VZOxyoXhACGIAKIIAKIiMKEBkzTq/6P08iguJR42YR4m8SD1ZhcmlvdXMgQXJ0aXN0cygCMAI48NMIQARSFAoEaXNyYxIMSEtJMTk5MjkzODAxWgYIAAgBGgBiGAoU6uTIKy4DL2owO/XYK+X5rhYc5aMQAmIYChRLRQEjLA2LTkur08u+z/sHZGqyXRABYhgKFOaFMNgZqHpPAmZ/rtIKJT1hSmdIEABiGAoU7t4VUT0DR0tIbxdhwfSfPx5W04cQBGICEAV6GAoUtkRXwvDrRoKhqPt8Kigf9+wRrR0QBg=="]}
[NOTICE] spotify:track:1Poipw3kkazL6Nitxo5f30 is NOT available!
[DEBUG] sent {"args":["mp3160",false],"name":"sp/track_uri","id":"4"}
```

I think this is because "is_available" is misinforming. Here is the restriction that comes with the track object:

```
restriction {
  catalogue: AD
  catalogue: SUBSCRIPTION
  countries_forbidden: ""
}
```

**Comment by kendersec** [comment]
I've modified the allowed condition to be:

```
allowed = len(allowed_countries) == 0 or self.country in allowed
```

I don't think we should have forbidden_countries as part of that condition at all as that element is already considered in forbidden later and they are both combined at the end.

**Comment by Hexxeh** [comment]
I've done some more jiggling around with this and I'm fairly happy with it. Closing this for now, feel free to reopen an issue if you have more problems.
